before_script:
  - git config --global user.email "washington@viewup.com.br"
  - git config --global user.name "Washington (Servidor Local)"

stages:
  - build
  - test

build_lib:
  stage: build
  script:
    - npm install
    - npm run tsc-build
    - npm run document
    - echo "test again" >> /var/www/viewup-cielo-node/test.txt
    - mkdir  -p  /var/www/viewup-cielo-node
    - mv $CI_PROJECT_DIR/docs/index.html /var/www/viewup-cielo-node/index.html
    - mv $CI_PROJECT_DIR/docs/README.md /var/www/viewup-cielo-node/README.md
    - rm -rf /var/www/viewup-cielo-node/vendor
    - mv $CI_PROJECT_DIR/docs/vendor /var/www/viewup-cielo-node/vendor

  tags:
      - cielo
      - dev-ops
      - ecommerce
      - viewup
document:
  stage: test
  script:
    - npm test
  only:
    - master
  tags:
    - cielo
    - dev-ops
    - ecommerce
    - viewup

#after_script:
#  - rm -rf $CI_PROJECT_DIR