before_script:
  - ls
  - git config --global user.email "washington@viewup.com.br"
  - git config --global user.name "Washington (Servidor Local)"

stages:
  - build
  - test

build_lib:
  stage: build
  script:
    - npm install
    - npm run tsc-build
  tags:
      - cielo
      - dev-ops
      - ecommerce
      - viewup
document:
  stage: test
  script:
    - echo "test again" >> /var/www/viewup-cielo-node/test.txt
    - echo $CI_PROJECT_DIR/docs
    - docsify init $CI_PROJECT_DIR/docs
    - ls
    - mkdir  -p  /var/www/viewup-cielo-node
    - mv $CI_PROJECT_DIR/docs/index.html /var/www/viewup-cielo-node/index.html
    - mv $CI_PROJECT_DIR/docs/README.md /var/www/viewup-cielo-node/README.md
  only:
    - master
  tags:
    - cielo
    - dev-ops
    - ecommerce
    - viewup