before_script:
  - git config --global user.email "washington@viewup.com.br"
  - git config --global user.name "Washington (Servidor Local)"

stages:
  - build
  - test

build_lib:
  stage: build
  script:
    - npm install
    - npm run document
    - mkdir  -p  /var/www/viewup-cielo-node
    - echo $CI_COMMIT_REF_SLUG > e
    - mv $CI_PROJECT_DIR/docs/index.html /var/www/viewup-cielo-node/index.html
    - mv $CI_PROJECT_DIR/docs/README.md /var/www/viewup-cielo-node/README.md
    - rm -rf /var/www/viewup-cielo-node/vendor
    - mv $CI_PROJECT_DIR/docs/vendor /var/www/viewup-cielo-node/vendor

  tags:
      - cielo
      - dev-ops
      - ecommerce
      - viewup
test_code:
  stage: test
  script:
    - npm install
    - npm run tsc-build
    - npm run app_test
  only:
    - master
  tags:
    - cielo
    - dev-ops
    - ecommerce
    - viewup