before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - git config --global user.email "washington@viewup.com.br"
  - git config --global user.name "Washington (Servidor Local)"

stages:
  - build
  - test
  - deploy

build_lib:
  stage: build
  script:
    - npm install
    - npm run document
    - npm run change
    - mkdir  -p  /var/www/viewup-cielo-node
    - echo $CI_COMMIT_REF_SLUG > e
    - mv $CI_PROJECT_DIR/docs/index.html /var/www/viewup-cielo-node/index.html
    - mv $CI_PROJECT_DIR/docs/README.md /var/www/viewup-cielo-node/README.md
    - rm -rf /var/www/viewup-cielo-node/vendor
    - mv $CI_PROJECT_DIR/docs/vendor /var/www/viewup-cielo-node/vendor

  tags:
      - cielo
      - dev-ops
      - ecommerce
      - viewup
test_code:
  stage: test
  script:
    - npm install
    - npm run tsc-build
    - npm run app_test
  only:
    - master
  tags:
    - cielo
    - dev-ops
    - ecommerce
    - viewup
deploy:
  stage: deploy
  script:
    - npm install
    - npm run tsc-build
    - npm run document
    - npm run dist
  only:
    - master
  tags:
    - cielo
    - dev-ops
    - ecommerce
    - viewup