before_script:
  - npm install -g docify
  - npm install
after_script:
  - mkdir /var/www/viewup-cielo-node
  - mv ./docs/index.html /var/www/viewup-cielo-node/index.html
  - mv ./docs/README.md /var/www/viewup-cielo-node/README.md

stages:
    - build
    - test
    - deploy

document:
  stage: build
  script:
    - npm run document
  only:
    - master
  tags:
    - documentation