before_script:
  - npm install -g docify
  - npm install
after_script:
  - mkdir  -p  /var/www/viewup-cielo-node
  - mv ./docs/index.html /var/www/viewup-cielo-node/index.html
  - mv ./docs/README.md /var/www/viewup-cielo-node/README.md

stages:
    - test

document:
  stage: test
  script:
    - npm install -g docify
    - npm install
    - docsify init ./docs
    - ls
  only:
    - master
  tags:
    - cielo
    - dev-ops
    - ecommerce
    - viewup