before_script:
  - ls
  - git config --global user.email "washington@viewup.com.br"
  - git config --global user.name "Washington (Servidor Local)"
after_script:
  - mkdir  -p  /var/www/viewup-cielo-node
  - mv ./docs/index.html /var/www/viewup-cielo-node/index.html
  - mv ./docs/README.md /var/www/viewup-cielo-node/README.md

stages:
    - test

document:
  stage: test
  script:
    - docify init ./docs
    - ls
  only:
    - master
  tags:
    - cielo
    - dev-ops
    - ecommerce
    - viewup